[package]
name = "plus9k"
version = "0.1.0"
authors = ["Dennis Sivia <dev@d-coded.de>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = "0.12.12"
regex = "1.11.1"
