name: GitHub CI

on:
  push:
    tags:
      - "!*"

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build, test and containerize
    steps:
      - uses: actions/checkout@v1
      - name: Build app
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
