name: Rust

# create ref_type: tag
# https://developer.github.com/v3/activity/events/types/#createevent
on: [create]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test
    - name: Release docker image
      run: ./scripts/release.bash
